# Generated by Django 5.0.3 on 2024-03-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
