# Generated by Django 5.0.3 on 2024-03-15 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0002_exchange_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaySymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("adj_close", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.IntegerField()),
                ("obv", models.BigIntegerField()),
                ("obv_signal", models.IntegerField()),
                ("obv_signal_sum", models.IntegerField()),
                ("price_diff", models.FloatField()),
                ("thirty_price_diff", models.FloatField()),
                ("thirty_close_trend", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zimuabull.symbol",
                    ),
                ),
            ],
        ),
    ]
