# Generated by Django 5.0.3 on 2024-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0003_daysymbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysymbol",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUY", "Buy"),
                    ("SELL", "Sell"),
                    ("HOLD", "Hold"),
                    ("STRONG_BUY", "Strong Buy"),
                    ("STRONG_SELL", "Strong Sell"),
                    ("NA", "Na"),
                ],
                default="NA",
                max_length=20,
            ),
        ),
    ]
