# Generated by Django 5.0.3 on 2024-08-26 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0006_remove_exchange_close_bucket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("buy_price", models.FloatField()),
                ("sell_price", models.FloatField()),
                ("diff", models.FloatField()),
                (
                    "prediction",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zimuabull.symbol",
                    ),
                ),
            ],
        ),
    ]
