# Generated by Django 5.0.3 on 2024-08-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0007_dayprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayprediction",
            name="buy_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayprediction",
            name="sell_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
