# Generated by Django 5.0.3 on 2024-08-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0008_dayprediction_buy_date_dayprediction_sell_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysymbol",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
