# Generated by Django 5.0.3 on 2024-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0009_daysymbol_accuracy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daysymbol",
            name="accuracy",
        ),
        migrations.AddField(
            model_name="symbol",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
