# Generated by Django 4.2.3 on 2025-10-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zimuabull", "0011_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("country", models.CharField(max_length=100)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchase_date", models.DateField()),
                ("purchase_notes", models.TextField(blank=True, null=True)),
                ("sell_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("sell_date", models.DateField(blank=True, null=True)),
                ("sell_notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SOLD", "Sold"), ("PARTIAL", "Partial")], default="ACTIVE", max_length=20)),
                ("stop_loss_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("target_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="holdings", to="zimuabull.portfolio")),
                ("symbol", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zimuabull.symbol")),
            ],
            options={
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_invested", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gain_loss", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gain_loss_percent", models.DecimalField(decimal_places=4, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="zimuabull.portfolio")),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("portfolio", "date")},
            },
        ),
    ]
