# Generated by Django 4.2.3 on 2025-10-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0013_conversation_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='daysymbol',
            name='macd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daysymbol',
            name='macd_histogram',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daysymbol',
            name='macd_signal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daysymbol',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SignalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previous_signal', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('STRONG_BUY', 'Strong Buy'), ('STRONG_SELL', 'Strong Sell'), ('NA', 'Na')], max_length=20, null=True)),
                ('new_signal', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('STRONG_BUY', 'Strong Buy'), ('STRONG_SELL', 'Strong Sell'), ('NA', 'Na')], max_length=20)),
                ('price', models.FloatField()),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('prediction', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_history', to='zimuabull.symbol')),
            ],
            options={
                'verbose_name_plural': 'Signal histories',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='zimuabull_s_symbol__eb64cc_idx'), models.Index(fields=['new_signal', '-date'], name='zimuabull_s_new_sig_098c65_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketIndexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='zimuabull.marketindex')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['index', '-date'], name='zimuabull_m_index_i_97fd77_idx')],
                'unique_together': {('index', 'date')},
            },
        ),
    ]
