# Generated by Django 4.2.3 on 2025-10-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0014_marketindex_daysymbol_macd_daysymbol_macd_histogram_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayTradingRecommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recommendation_date", models.DateField()),
                ("rank", models.IntegerField()),
                ("confidence_score", models.FloatField()),
                ("recommended_allocation", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entry_price", models.FloatField()),
                ("target_price", models.FloatField(blank=True, null=True)),
                ("stop_loss_price", models.FloatField(blank=True, null=True)),
                ("signal_score", models.FloatField()),
                ("momentum_score", models.FloatField()),
                ("volume_score", models.FloatField()),
                ("prediction_score", models.FloatField()),
                ("technical_score", models.FloatField()),
                ("actual_high", models.FloatField(blank=True, null=True)),
                ("actual_low", models.FloatField(blank=True, null=True)),
                ("actual_close", models.FloatField(blank=True, null=True)),
                ("actual_return", models.FloatField(blank=True, null=True)),
                ("hit_target", models.BooleanField(blank=True, null=True)),
                ("recommendation_reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="day_trade_recommendations", to="zimuabull.symbol")),
            ],
            options={
                "ordering": ["recommendation_date", "rank"],
                "indexes": [models.Index(fields=["-recommendation_date", "rank"], name="zimuabull_d_recomme_e7c8ec_idx"), models.Index(fields=["symbol", "-recommendation_date"], name="zimuabull_d_symbol__da175f_idx")],
                "unique_together": {("symbol", "recommendation_date")},
            },
        ),
    ]
