# Generated by Django 4.2.3 on 2025-10-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0017_alter_portfolioholding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zimuabull.symbol'),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('CALL', 'Call'), ('PUT', 'Put')], max_length=15),
        ),
    ]
