# Generated by Django 4.2.3 on 2025-10-08 11:51

import django.db.models.deletion
from django.db import migrations, models


def migrate_portfolios_to_exchange(apps, schema_editor):
    """Map existing portfolios to exchanges based on country"""
    Portfolio = apps.get_model("zimuabull", "Portfolio")
    Exchange = apps.get_model("zimuabull", "Exchange")

    # Create a mapping of country to exchange
    country_to_exchange = {}
    for exchange in Exchange.objects.all():
        if exchange.country not in country_to_exchange:
            country_to_exchange[exchange.country] = exchange

    # Update portfolios
    for portfolio in Portfolio.objects.all():
        if hasattr(portfolio, "country") and portfolio.country in country_to_exchange:
            portfolio.exchange = country_to_exchange[portfolio.country]
            portfolio.save()


class Migration(migrations.Migration):

    dependencies = [
        ("zimuabull", "0018_portfoliotransaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="exchange",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="zimuabull.exchange"),
        ),
        migrations.RunPython(migrate_portfolios_to_exchange, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="portfolio",
            name="country",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="currency",
        ),
    ]
