# Generated by Django 4.2.3 on 2025-10-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0023_daytradeposition'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='daytradeposition',
            new_name='zimuabull_d_portfol_da33fc_idx',
            old_name='zimuabull_d_portfol_9b9eed_idx',
        ),
        migrations.RenameIndex(
            model_name='daytradeposition',
            new_name='zimuabull_d_symbol__37ec42_idx',
            old_name='zimuabull_d_symbol__c8a8d4_idx',
        ),
        migrations.RenameIndex(
            model_name='daytradeposition',
            new_name='zimuabull_d_status_d79b14_idx',
            old_name='zimuabull_d_status_bace6b_idx',
        ),
        migrations.RenameIndex(
            model_name='featuresnapshot',
            new_name='zimuabull_f_trade_d_afdb6c_idx',
            old_name='zimuabull_f_trade_d_27d50c_idx',
        ),
        migrations.RenameIndex(
            model_name='featuresnapshot',
            new_name='zimuabull_f_symbol__a9f5d6_idx',
            old_name='zimuabull_f_symbol__0a16f5_idx',
        ),
        migrations.RenameIndex(
            model_name='intradaypricesnapshot',
            new_name='zimuabull_i_symbol__8c7452_idx',
            old_name='zimuabull_i_symbol__287253_idx',
        ),
        migrations.RenameIndex(
            model_name='intradaypricesnapshot',
            new_name='zimuabull_i_timesta_4de691_idx',
            old_name='zimuabull_i__times_3dccaa_idx',
        ),
    ]
