# Generated by Django 4.2.3 on 2025-10-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0024_rename_zimuabull_d_portfol_9b9eed_idx_zimuabull_d_portfol_da33fc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News articles',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymbolNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimuabull.news')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimuabull.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.IntegerField()),
                ('justification', models.TextField()),
                ('description', models.TextField()),
                ('model_name', models.CharField(default='gpt-4.1-mini', max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='zimuabull.news')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='symbols',
            field=models.ManyToManyField(related_name='news_articles', through='zimuabull.SymbolNews', to='zimuabull.symbol'),
        ),
        migrations.AddIndex(
            model_name='symbolnews',
            index=models.Index(fields=['symbol', '-created_at'], name='zimuabull_s_symbol__b147e5_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolnews',
            index=models.Index(fields=['news'], name='zimuabull_s_news_id_961c38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='symbolnews',
            unique_together={('symbol', 'news')},
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_date'], name='zimuabull_n_publish_eecc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-created_at'], name='zimuabull_n_created_010968_idx'),
        ),
    ]
