# Generated by Django 4.2.3 on 2025-10-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0025_news_symbolnews_newssentiment_news_symbols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='dt_allow_fractional_shares',
            field=models.BooleanField(default=False, help_text='If True, allows fractional share purchases. If False, rounds to whole shares only.'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dt_max_position_percent',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Maximum percentage of portfolio to allocate per position (e.g., 0.25 = 25%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dt_max_recommendations',
            field=models.IntegerField(default=50, help_text='Maximum number of positions to open in morning trading session'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dt_per_trade_risk_fraction',
            field=models.DecimalField(decimal_places=3, default=0.02, help_text='Risk fraction per trade for position sizing (e.g., 0.02 = 2% portfolio risk)', max_digits=4),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='If True, portfolio will execute autonomous day trading algorithm. If False, manual tracking only.'),
        ),
    ]
