# Generated by Django 4.2.3 on 2025-10-15 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0026_portfolio_dt_allow_fractional_shares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHoldingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREATE', 'Create Holding'), ('UPDATE', 'Update Holding'), ('DELETE', 'Delete Holding'), ('SELL_ERROR', 'Sell Error - Holding Not Found')], max_length=20)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('average_cost_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('average_cost_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(max_length=15)),
                ('transaction_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('holding_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_logs', to='zimuabull.portfolio')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimuabull.symbol')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zimuabull.portfoliotransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='zimuabull_p_portfol_8e5328_idx'), models.Index(fields=['symbol', '-created_at'], name='zimuabull_p_symbol__e5768c_idx'), models.Index(fields=['transaction'], name='zimuabull_p_transac_8519c5_idx'), models.Index(fields=['operation', '-created_at'], name='zimuabull_p_operati_9da4b7_idx')],
            },
        ),
    ]
