# Generated by Django 4.2.3 on 2025-10-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0027_portfolioholdinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ib_account',
            field=models.CharField(blank=True, help_text='Interactive Brokers account number (optional, use if you have multiple accounts)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ib_client_id',
            field=models.IntegerField(blank=True, default=1, help_text='Unique client ID for this connection (1-999). Each portfolio should use a different client ID.', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ib_host',
            field=models.CharField(blank=True, default='127.0.0.1', help_text='Interactive Brokers Gateway/TWS host address (e.g., 127.0.0.1 or 192.168.0.85)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ib_is_paper',
            field=models.BooleanField(default=True, help_text='If True, uses IB paper trading account. If False, uses live trading account. CAUTION: Live trading uses real money!'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ib_port',
            field=models.IntegerField(blank=True, default=4001, help_text='Interactive Brokers port number (4001 for IB Gateway live, 4002 for paper, 7497 for TWS live, 7496 for TWS paper)', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='use_interactive_brokers',
            field=models.BooleanField(default=False, help_text='If True, trades will be executed via Interactive Brokers API. If False, trades are paper/simulated only.'),
        ),
    ]
