# Generated by Django 4.2.3 on 2025-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0028_portfolio_ib_account_portfolio_ib_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioholdinglog',
            name='operation',
            field=models.CharField(choices=[('CREATE', 'Create Holding'), ('UPDATE', 'Update Holding'), ('DELETE', 'Delete Holding'), ('SELL_ERROR', 'Sell Error - Holding Not Found'), ('SELL_CORRECTION', 'Sell Correction - Orphaned Holding Cleanup')], max_length=20),
        ),
    ]
