# Generated by Django 4.2.3 on 2025-10-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0029_alter_portfolioholdinglog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytradeposition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='IBOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ib_order_id', models.IntegerField(blank=True, null=True)),
                ('ib_perm_id', models.IntegerField(blank=True, null=True)),
                ('client_order_id', models.CharField(max_length=100, unique=True)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('MKT', 'Market'), ('LMT', 'Limit'), ('STP', 'Stop'), ('STP LMT', 'Stop Limit')], default='MKT', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('submitted_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('filled_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_trade_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_orders', to='zimuabull.daytradeposition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_orders', to='zimuabull.portfolio')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_orders', to='zimuabull.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='zimuabull_i_portfol_1e238d_idx'), models.Index(fields=['status', '-created_at'], name='zimuabull_i_status_a2117a_idx'), models.Index(fields=['ib_order_id'], name='zimuabull_i_ib_orde_eed12d_idx'), models.Index(fields=['day_trade_position'], name='zimuabull_i_day_tra_4dc998_idx')],
            },
        ),
    ]
