# Generated by Django 4.2.3 on 2025-10-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zimuabull', '0033_marketregime'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketregime',
            new_name='zimuabull_m_index_i_2e4466_idx',
            old_name='zimuabull_m_index__d95418_idx',
        ),
        migrations.RenameIndex(
            model_name='marketregime',
            new_name='zimuabull_m_regime_626300_idx',
            old_name='zimuabull_m_regime_627037_idx',
        ),
        migrations.RenameIndex(
            model_name='modelversion',
            new_name='zimuabull_m_feature_477d31_idx',
            old_name='zimuabull_m_feature_a7f265_idx',
        ),
        migrations.RenameIndex(
            model_name='modelversion',
            new_name='zimuabull_m_is_acti_ad982b_idx',
            old_name='zimuabull_m_is_acti_78b0b9_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioriskmetrics',
            new_name='zimuabull_p_portfol_3f9d71_idx',
            old_name='zimuabull_p_portfol_2d1948_idx',
        ),
    ]
