version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - environment.prod
    volumes:
      - .db_data/db.sqlite3:/db.sqlite3  # Persist the SQLite database file
    depends_on:
      - redis  # Ensure Redis starts before the web service
    command: >
      sh -c "
         if [ ! -d /code ]; then
          mkdir -p /code;
        fi &&
        if [ ! -d /code/.git ]; then
            git clone https://github.com/dominicplouffe/ZimuaBull /code;
        else
            cd /code && git pull origin master;
        fi &&
        cd /code &&
        pip install --upgrade pip setuptools wheel
        pip install lxml numpy pandas --extra-index-url https://www.piwheels.org/simple &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        supervisord -c /etc/supervisor/supervisord.conf &&
        python manage.py runserver 0.0.0.0:8000
      "
  redis:
    image: redis:latest
    ports:
      - "6379:6379"