# Generated by Django 4.2.3 on 2024-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=200)),
                ("temperature", models.FloatField()),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("feels_like", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("wind_speed", models.IntegerField()),
                ("wind_direction", models.IntegerField()),
                ("cloud_cover", models.IntegerField()),
                ("visibility", models.IntegerField()),
                ("uv_index", models.IntegerField()),
                ("sunrise", models.DateTimeField()),
                ("sunset", models.DateTimeField()),
                ("minutely", models.JSONField()),
                ("hourly", models.JSONField()),
                ("daily", models.JSONField()),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Weather",
            },
        ),
    ]
