# Generated by Django 4.2.3 on 2024-12-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('section_name', models.CharField(max_length=255)),
                ('section_category', models.CharField(max_length=255)),
                ('section_question', models.TextField()),
                ('section_responses', models.TextField()),
                ('function_name', models.CharField(max_length=255)),
                ('function_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbook.playbook')),
            ],
        ),
    ]
