# Generated by Django 4.2.3 on 2024-12-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooksections',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='playbooksections',
            name='function_type',
        ),
        migrations.RemoveField(
            model_name='playbooksections',
            name='section_responses',
        ),
    ]
